baseurl = "http://nho1ix.github.io/"
languageCode = "en-us"
title = "Vic's Gallery"
theme = "autophugo"
disableKinds = ["taxonomy", "term"]

[Author]
    name = "Victor Vo"
    email = "fromvictorvo@gmail.com"

[params]
    column_count = 4
    thumb_width = 480
    full_width = 1440

    [[params.footer.social.links]]
    label = "Instagram"
    url = "https://instagram.com/victorvo.photo"
    icon = "fa-instagram"
